{
  "DATA_SOURCE": {
    "dataset": "dryad_blg59",
    "input_root": "/home/daniel/Mapper-Design/mapper-data-root/LBNL_DRYAD_BLDG59"
  },
  "output_root": "/home/daniel/Mapper-Design/mapper-data-root/LBNL_DRYAD_BLDG59/mapper-data",
  "s01_data": {
    "io": {
      "max_workers": 1,
      "chunk_len": 8192
    }
  },
  "exec": {
    "reporting": {
      "console": true,
      "progress": true,
      "progress_style": "single_line",
      "progress_every": 10,
      "progress_min_seconds": 1.0,
      "show_eta": true
    }
  }
}
